#!/bin/bash
# exBOMBER
# -------------------------------------------------------
# exBOMBER: A linux server hack/exploit finder
# version: .01
# Github: https://github.com/InterGenStudios
# ---------------------------------------------------
# InterGenStudios: 7-25-15
# Copyright (c) 2015: Christopher 'InterGen' Cork  InterGenStudios
# --------------------------------
# License: GPL-2.0+
# URL: http://opensource.org/licenses/gpl-license.php
# ---------------------------------------------------
# exBOMBER is free software:
# You may redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your discretion)
# any later version.
# ------------------


# To Do List
#-----------
# NEED TO ASK FOR SUPPORT TICKET INFO TO APPEND TO EMAIL SUBJECT IN GET_NOTIFY_DESTINATION ()- WILL BE HELPFULL FOR HELPDESKS
# NEED TO ID MAILSERVER TO ALLOW FOR ISSUING CORRECT MAIL COMMAND
# - CURRENTLY ASSUMING SENDMAIL
# NEED TO DEVELOP PHP_SITE_SCAN RE: http://www.gregfreeman.org/2013/how-to-tell-if-your-php-site-has-been-compromised/

###########################################
##---------------------------------------##
## BEGIN - INITIAL VARIABLE DECLARATIONS ##
##---------------------------------------##
###########################################

# Set timestamp
TIMESTAMP="$(date +"%m-%d-%Y:%T")"

RED="\e[1m\e[31m"
GREEN="\e[1m\e[32m"
YELLOW="\e[1m\e[33m"
BLUE="\e[1m\e[34m"
CYAN="\e[1m\e[36m"
WHITE="\e[1m\e[37m"
NOCOLOR="\e[0m"
BLINK="\e[5m"
UNDERLINE_TEXT="\e[4m"

#########################################
##-------------------------------------##
## END - INITIAL VARIABLE DECLARATIONS ##
##-------------------------------------##
#########################################

##############################
##--------------------------##
## BEGIN - SCRIPT FUNCTIONS ##
##--------------------------##
##############################

#----------------------------------#
# BEGIN - DISPLAY LAYOUT FUNCTIONS #
#----------------------------------#

# Simple divider
DIVIDER () {

    echo -e "\n${BLUE}---------------------------------------------------------${NOCOLOR}\n"

}

# Creates uniform look during script execution when called after any clear command
HEADER () {

    echo -e "\n${BLUE}====================================================================================${NOCOLOR}"
    echo -e "${BLUE}===[ ${WHITE}ex${CYAN}BOMBER ${WHITE}version${GREEN}.01 ${BLUE}]================================[ ${WHITE}$TIMESTAMP ${BLUE}]===${NOCOLOR}"
    echo -e "${BLUE}====================================================================================${NOCOLOR}\n\n"

}

#--------------------------------#
# END - DISPLAY LAYOUT FUNCTIONS #
#--------------------------------#

GET_INSTRUCTIONS () {

    clear
    HEADER
    echo -e "    ${GREEN}${UNDERLINE_TEXT}Select an operation${NOCOLOR}:\n\n"
    echo -e "    ${WHITE}1) ${GREEN}Findbot.pl      ${NOCOLOR}(${WHITE}1-i${NOCOLOR} for info)"
    echo -e "    ${WHITE}2) ${GREEN}Maldet          ${NOCOLOR}(${WHITE}2-i${NOCOLOR} for info)"
    echo -e "    ${WHITE}3) ${GREEN}PHP Site Scan   ${NOCOLOR}(${WHITE}3-i${NOCOLOR} for info)\n"
    echo -e -n "    [${WHITE}${UNDERLINE_TEXT}Enter Selection${NOCOLOR}]: "
    read -r get_instructions
    case $get_instructions in
        1) mkdir -p /root/support/exBOMBER/tmp
           echo SCAN_TYPE = FB > /root/support/exBOMBER/tmp/scan_config
           SCAN_TYPE=FB
           mkdir -p /var/log/exb_logs/findbot
           CHECK_FOR_FINDBOT 2>&1 | tee /var/log/exb_logs/findbot/chk_fbt_"$TIMESTAMP"
           sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
           -e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
           -e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/findbot/chk_fbt_"$TIMESTAMP"
           EXEC_FINDBOT 2>&1 | tee /var/log/exb_logs/findbot/exec_fbt_"$TIMESTAMP"
           sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
           -e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
           -e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/findbot/exec_fbt_"$TIMESTAMP"
            ;;
        2) mkdir -p /root/support/exBOMBER/tmp
           echo SCAN_TYPE = MD > /root/support/exBOMBER/tmp/scan_config
           SCAN_TYPE=MD
           mkdir -p /var/log/exb_logs/maldet
           CHECK_FOR_MALDET 2>&1 | tee /var/log/exb_logs/maldet/chk_mldt_"$TIMESTAMP"
           sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
           -e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
           -e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/maldet/chk_mldt_"$TIMESTAMP"
           EXEC_MALDET 2>&1 | tee /var/log/exb_logs/maldet/exec_mldt_"$TIMESTAMP"
           sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
           -e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
           -e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/maldet/exec_mldt_"$TIMESTAMP"
            ;;
        3) mkdir -p /root/support/exBOMBER/tmp
           echo SCAN_TYPE = PS > /root/support/exBOMBER/tmp/scan_config
           SCAN_TYPE=PS
           mkdir -p /var/log/exb_logs/php_scan
           EXEC_PHP_SITE_SCAN 2>&1 | tee /var/log/exb_logs/php_scan/site_scan_"$TIMESTAMP"
           sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
           -e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
           -e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/php_scan/site_scan_"$TIMESTAMP"
            ;;
        1-i) FINDBOT_HELPTEXT
            ;;
        2-i) MALDET_HELPTEXT
            ;;
        3-i) PHP_SITE_SCAN_HELPTEXT
            ;;
        *) printf "\n"
           echo -e "    ${RED}${BLINK}INVALID SELECTION${NOCOLOR}\n\n    Please choose again"
           sleep 2
           GET_INSTRUCTIONS
            ;;
    esac
}

FINDBOT_HELPTEXT () {

    clear
    HEADER
    echo -e "    ${WHITE}FINDBOT.PL HELPTEXT${NOCOLOR}"
    DIVIDER
    echo -e "    This script attempts to find malicious files/scripts on your machine. It"
    echo -e "    specifically looks for known documented spambots, as well as ${WHITE}\"suspicious\"${NOCOLOR}"
    echo -e "    constructs in various scripting languages.\n"
    echo -e "    By default, findbot.pl scans the directories ${WHITE}/tmp, /usr/tmp, /home,${NOCOLOR} and"
    echo -e "    ${WHITE}/var/www${NOCOLOR}.  This script isn't fast, so if you know where to look you can"
    echo -e "    speed things up by passing it only the directories that you suspect"
    echo -e "    contain malware.\n"
    echo -e "    ${WHITE}${UNDERLINE_TEXT}ex${CYAN}BOMBER ${WHITE}FINDBOT.PL Options${NOCOLOR}:\n"
    echo -e "        ${WHITE}ES${NOCOLOR} - Scans the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver"
    echo -e "        ${WHITE}DD${NOCOLOR} - Scans the ${WHITE}D${NOCOLOR}efault ${WHITE}D${NOCOLOR}irectories:"
    echo -e "             ${WHITE}/tmp, /usr/tmp, /home, ${NOCOLOR}and ${WHITE}/var/www${NOCOLOR}"
    echo -e "        ${WHITE}CP${NOCOLOR} - Scans the user provided ${WHITE}C${NOCOLOR}ustom ${WHITE}P${NOCOLOR}ath\n"
    echo -e "    ${WHITE}${UNDERLINE_TEXT}Results${NOCOLOR}:\n"
    echo -e "        There are two types of ${WHITE}\"detections\"${NOCOLOR}:\n"
    echo -e "            ${WHITE}\"suspicious files\"${NOCOLOR} are files that contain things that -may- be"
    echo -e "            malicious.\n"
    echo -e "            ${WHITE}\"malware\"${NOCOLOR} is definitely malicious software.\n"
    echo -e "        FINDBOT.PL scan logs will be written to:\n"
    echo -e "            ${WHITE}/var/log/exb_logs/findbot/${NOCOLOR}<log>\n"
    echo -e "        A pastebin of the log will also be provided.\n\n\n"
    echo -e -n "    [ ${CYAN}M${NOCOLOR} ] ${WHITE}Menu${NOCOLOR} | [ ${CYAN}Q${NOCOLOR} ] ${WHITE}Quit${NOCOLOR} : "
    read -r FHT_CHOICE
    case "$FHT_CHOICE" in

    [m,M]) GET_INSTRUCTIONS
            ;;
    [q,Q]) printf "\n\n\n"
           exit 0
            ;;
        *) echo -e "\n    ${RED}${BLINK}INVALID OPTION${NOCOLOR}"
           sleep 2
           FINDBOT_HELPTEXT
            ;;
    esac

}

MALDET_HELPTEXT () {

    clear
    HEADER
    echo -e "    ${WHITE}MALDET HELPTEXT${NOCOLOR}"
    DIVIDER
    echo -e "    ${GREEN}Detailed Information here${NOCOLOR} ${YELLOW}===> ${WHITE}https://www.rfxn.com/appdocs/README.maldetect${NOCOLOR}\n"
    echo -e "    Linux Malware Detect (LMD) is a malware scanner for Linux released under the"
    echo -e "    GNU GPLv2 license, that is designed around the threats faced in shared hosted"
    echo -e "    environments. It uses threat data from network edge intrusion detection systems"
    echo -e "    to extract malware that is actively being used in attacks and generates"
    echo -e "    signatures for detection. In addition, threatdata is also derived from user"
    echo -e "    submissions with the LMD checkout feature and from malware community resources."
    echo -e "    The signatures that LMD uses are MD5 file hashes and HEX pattern matches, they"
    echo -e "    are also easily exported to any number of detection tools such as ClamAV.\n"
    echo -e "    ${WHITE}${UNDERLINE_TEXT}ex${CYAN}BOMBER ${WHITE}MALDET Options${NOCOLOR}:\n"
    echo -e "        ${WHITE}ES${NOCOLOR} - Scans the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver"
    echo -e "        ${WHITE}UD${NOCOLOR} - Scans the ${WHITE}U${NOCOLOR}ser ${WHITE}D${NOCOLOR}irectories:"
    echo -e "             ${WHITE}/home/*${NOCOLOR}"
    echo -e "        ${WHITE}CP${NOCOLOR} - Scans the user provided ${WHITE}C${NOCOLOR}ustom ${WHITE}P${NOCOLOR}ath\n"
    echo -e "    ${WHITE}${UNDERLINE_TEXT}Results${NOCOLOR}:\n"
    echo -e "        In addition to Maldet's default logs, ${WHITE}ex${CYAN}BOMBER${NOCOLOR} Maldet scan logs will be"
    echo -e "        written to:\n"
    echo -e "            ${WHITE}/var/log/exb_logs/maldet/${NOCOLOR}<log>\n"
    echo -e "        A pastebin of the log will also be provided.\n\n\n"
    echo -e -n "    [ ${CYAN}M${NOCOLOR} ] ${WHITE}Menu${NOCOLOR} | [ ${CYAN}Q${NOCOLOR} ] ${WHITE}Quit${NOCOLOR} : "
    read -r MHT_CHOICE
    case "$MHT_CHOICE" in

    [m,M]) GET_INSTRUCTIONS
            ;;
    [q,Q]) printf "\n\n\n"
           exit 0
            ;;
        *) echo -e "\n    ${RED}${BLINK}INVALID OPTION${NOCOLOR}"
           sleep 2
           MALDET_HELPTEXT
            ;;
    esac

}

PHP_SITE_SCAN_HELPTEXT () {

    clear
    HEADER
    echo -e "    ${WHITE}PHP SITE SCAN HELPTEXT${NOCOLOR}"
    DIVIDER
    echo -e "    ${YELLOW}IN DEVELOPMENT\n\n\n"
    echo -e -n "    [ ${CYAN}M${NOCOLOR} ] ${WHITE}Menu${NOCOLOR} | [ ${CYAN}Q${NOCOLOR} ] ${WHITE}Quit${NOCOLOR} : "
    read -r PHT_CHOICE
    case "$PHT_CHOICE" in

    [m,M]) GET_INSTRUCTIONS
            ;;
    [q,Q]) printf "\n\n\n"
           exit 0
            ;;
        *) echo -e "\n    ${RED}${BLINK}INVALID OPTION${NOCOLOR}"
           sleep 2
           PHP_SITE_SCAN_HELPTEXT
            ;;
    esac

}

CHECK_FOR_FINDBOT () {

    if [ -f "/root/support/exBOMBER/findbot.pl" ]; then
        clear
        HEADER
        echo -e "    ${GREEN}FINDBOT.PL ${WHITE}is ${NOCOLOR}present on server\n\n"
        sleep .5
    else
        clear
        HEADER
        echo -e "    ${GREEN}FINDBOT.PL ${NOCOLOR}is ${WHITE}not${NOCOLOR} present on server\n\n"
        sleep .5
        echo -e "    Fetching FINDBOT.PL...\n"
        mkdir -p /root/support/exBOMBER
        wget -q http://cbl.abuseat.org/findbot.pl -P /root/support/exBOMBER && chmod +x /root/support/exBOMBER/findbot.pl
        sleep .5
        echo -e "    Script retrieved successfully\n"
        sleep .5
    fi

}

CHECK_FOR_MALDET () {

    if [ -f "/usr/local/maldetect/maldet" ]; then
        clear
        HEADER
        echo -e "    ${GREEN}MALDET ${WHITE}is ${NOCOLOR}present on server\n\n"
        sleep .5
        echo -e "    Updating malware signatures, stand by...\n"
        maldet -u > /dev/null 2>&1 && maldet -d > /dev/null 2>&1
        echo -e "    MALDET has been updated"
        sleep .5
    else
        clear
        HEADER
        echo -e "    ${GREEN}MALDET ${NOCOLOR}is ${WHITE}not${NOCOLOR} present on server\n\n"
        sleep .5
        echo -e "    Fetching MALDET...\n"
        mkdir -p /root/support/exBOMBER
        wget -q http://www.rfxn.com/downloads/maldetect-current.tar.gz -P /root/support/exBOMBER/
        cd /root/support/exBOMBER && tar xf /root/support/exBOMBER/maldetect-current.tar.gz
        echo -e "    Installing MALDET, stand by...\n"
        cd /root/support/exBOMBER/maldetect-* && /bin/bash install.sh > /dev/null 2>&1 &&
        rm -rf /root/support/exBOMBER/maldetect-current.tar.gz
        echo -e "    MALDET installed successfully\n"
        sleep .5
    fi

}

EXEC_FINDBOT () {

    clear
    HEADER
    echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}FINDBOT.PL MENU${NOCOLOR}"
    DIVIDER
    echo -e "    ${WHITE}${UNDERLINE_TEXT}Set the search path${NOCOLOR}\n\n"
    echo -e "        ${WHITE}1) ES - ${NOCOLOR}Scan the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver\n"
    echo -e "        ${WHITE}2) DD - ${NOCOLOR}Scan the ${WHITE}D${NOCOLOR}efault ${WHITE}D${NOCOLOR}irectories:\n"
    if [ "$PANEL" = "WHM" ] || [ "$PANEL" = "DirectAdmin" ]; then
        F_PATH_TYPE=TRI
        echo -e "                       ${WHITE}/tmp /usr/tmp /home${NOCOLOR}\n"
    else
        F_PATH_TYPE=QUAD
        echo -e "                       ${WHITE}/tmp /usr/tmp /home /var/www${NOCOLOR}\n"
    fi
    echo -e "        ${WHITE}3) CP - ${NOCOLOR}Scan a Custom Path\n\n"
    echo -e -n "    [${WHITE}Enter Selection ${NOCOLOR}1-3]: "
    read -r E_F_SELECTION
    case $E_F_SELECTION in
        1) tput cuu 2 && tput el
           echo SEARCH_PATHS = / >> /root/support/exBOMBER/tmp/scan_config
           SEARCH_PATHS="/"
           echo -e "\n    FINDBOT.PL will search the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver\n"
           echo -e "    ${YELLOW}-NOTE-${NOCOLOR} This search will take quite some time to complete\n\n"
           echo -e -n "    Enable Experimental ${WHITE}\"-c\"${NOCOLOR} (turbo) Option for FINDBOT.PL (${WHITE}y${NOCOLOR}/${WHITE}N${NOCOLOR})? "
           read -r F_TURBO_OPTION
           case $F_TURBO_OPTION in
                [y,Y]) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=ON
                       echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
                   -c) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=ON
                       echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
                    *) echo TURBO_OPTION = OFF >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=OFF
                       echo -e "\n    ${BLUE}TURBO OPTION DISABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
           esac
           GET_NOTIFY_DESTINATION
           ;;
        2) tput cuu 2 && tput el
           if [ "$F_PATH_TYPE" = "TRI" ]; then
               echo SEARCH_PATHS = /tmp /usr/tmp /home >> /root/support/exBOMBER/tmp/scan_config
               SEARCH_PATHS="/tmp /usr/tmp /home"
           else
               echo SEARCH_PATHS = /tmp /usr/tmp /home /var/www >> /root/support/exBOMBER/tmp/scan_config
               SEARCH_PATHS="/tmp /usr/tmp /home /var/www"
           fi
           echo -e "\n    FINDBOT.PL will search ${WHITE}$SEARCH_PATHS${NOCOLOR}\n"
           echo -e "    ${YELLOW}-NOTE-${NOCOLOR} This search will take quite some time to complete\n\n\n"
           case $F_TURBO_OPTION in
                [y,Y]) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=ON
                       echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
                   -c) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=ON
                       echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
                    *) echo TURBO_OPTION = OFF >> /root/support/exBOMBER/tmp/scan_config
                       TURBO_OPTION=OFF
                       echo -e "\n    ${BLUE}TURBO OPTION DISABLED${NOCOLOR}\n\n"
                       sleep 2
                       ;;
           esac
           GET_NOTIFY_DESTINATION
           ;;
        3) tput cuu 2 && tput el
           echo -e "\n    ${GREEN}-- ${WHITE}C${NOCOLOR}ustom ${WHITE}P${NOCOLOR}ath selected ${GREEN}--${NOCOLOR}   \n"
           echo -e -n "    [${WHITE}Enter Custom Path${NOCOLOR}]: "
           read -r CUSTOM_PATH
           if [ -d "$CUSTOM_PATH" ]; then
               tput cuu 2 && tput el
               echo -e "\n    FINDBOT.PL will search ${WHITE}$CUSTOM_PATH${NOCOLOR}\n\n"
               echo SEARCH_PATHS = "$CUSTOM_PATH" >> /root/support/exBOMBER/tmp/scan_config
               echo -e -n "    Enable Experimental ${WHITE}\"-c\"${NOCOLOR} (turbo) Option for FINDBOT.PL (${WHITE}y${NOCOLOR}/${WHITE}N${NOCOLOR})? "
               read -r F_TURBO_OPTION
               case $F_TURBO_OPTION in
                    [y,Y]) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                           TURBO_OPTION=ON
                           echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                           sleep 2
                           ;;
                       -c) echo TURBO_OPTION = ON >> /root/support/exBOMBER/tmp/scan_config
                           TURBO_OPTION=ON
                           echo -e "\n    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n\n"
                           sleep 2
                           ;;
                        *) echo TURBO_OPTION = OFF >> /root/support/exBOMBER/tmp/scan_config
                           TURBO_OPTION=OFF
                           echo -e "\n    ${BLUE}TURBO OPTION DISABLED${NOCOLOR}\n\n"
                           sleep 2
                           ;;
               esac
               GET_NOTIFY_DESTINATION
           else
               echo -e "\n    ${RED}${BLINK}INVALID PATH${NOCOLOR}\n\n\n\n"
               sleep 2
               EXEC_FINDBOT
           fi
           ;;
        *) echo -e "\n    ${RED}${BLINK}INVALID OPTION${NOCOLOR}\n\n\n\n"
           sleep 2
           EXEC_FINDBOT
           ;;
    esac

}

EXEC_MALDET () {

    clear
    HEADER
    echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}MALDET MENU${NOCOLOR}"
    DIVIDER
    echo -e "    ${WHITE}${UNDERLINE_TEXT}Set the search path${NOCOLOR}\n\n"
    echo -e "        ${WHITE}1) ES - ${NOCOLOR}Scan the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver\n"
    echo -e "        ${WHITE}2) UD - ${NOCOLOR}Scan the ${WHITE}U${NOCOLOR}ser ${WHITE}D${NOCOLOR}irectories:\n"
    if [ "$PANEL" = "WHM" ] || [ "$PANEL" = "DirectAdmin" ]; then
        M_PATH_TYPE=TRI
        echo -e "                       ${WHITE}/home${NOCOLOR}\n"
    else
        M_PATH_TYPE=QUAD
        echo -e "                       ${WHITE}/home /var/www${NOCOLOR}\n"
    fi
    echo -e "        ${WHITE}3) CP - ${NOCOLOR}Scan a Custom Path\n\n"
    echo -e -n "    [${WHITE}Enter Selection ${NOCOLOR}1-3]: "
    read -r E_M_SELECTION
    case $E_M_SELECTION in
        1) tput cuu 2 && tput el
           echo SEARCH_PATHS = / >> /root/support/exBOMBER/tmp/scan_config
           SEARCH_PATHS="/"
           echo -e "\n    MALDET will search the ${WHITE}E${NOCOLOR}ntire ${WHITE}S${NOCOLOR}erver\n"
           echo -e "    ${YELLOW}-NOTE-${NOCOLOR} This search will take quite some time to complete\n\n\n"
           sleep 2
           GET_NOTIFY_DESTINATION
           ;;
        2) tput cuu 2 && tput el
           if [ "$M_PATH_TYPE" = "TRI" ]; then
               SHOW_SEARCH_PATHS="/home/*/public_html"
               SEARCH_PATHS="/home/?/public_html"
               echo SEARCH_PATHS = /home/?/public_html >> /root/support/exBOMBER/tmp/scan_config
           else
               SHOW_SEARCH_PATHS="/var/www"
               SEARCH_PATHS="/var/www"
               echo SEARCH_PATHS = /var/www >> /root/support/exBOMBER/tmp/scan_config
           fi
           echo -e "\n    MALDET will search ${WHITE}$SHOW_SEARCH_PATHS${NOCOLOR}\n"
           echo -e "    ${YELLOW}-NOTE-${NOCOLOR} This search will take quite some time to complete\n\n\n"
           sleep 2
           GET_NOTIFY_DESTINATION
           ;;
        3) tput cuu 2 && tput el
           echo -e "\n    ${GREEN}-- ${WHITE}C${NOCOLOR}ustom ${WHITE}P${NOCOLOR}ath selected ${GREEN}--${NOCOLOR}   \n"
           echo -e -n "    [${WHITE}Enter Custom Path${NOCOLOR}]: "
           read -r CUSTOM_PATH
           if [ -d "$CUSTOM_PATH" ]; then
               tput cuu 2 && tput el
               echo SEARCH_PATHS = "$CUSTOM_PATH" >> /root/support/exBOMBER/tmp/scan_config
               echo -e "\n    MALDET will search ${WHITE}$CUSTOM_PATH${NOCOLOR}\n\n\n\n"
               sleep 2
               GET_NOTIFY_DESTINATION
           else
               echo -e "\n    ${RED}${BLINK}INVALID PATH${NOCOLOR}\n\n\n\n"
               sleep 2
               EXEC_MALDET
           fi
           ;;
        *) echo -e "\n    ${RED}${BLINK}INVALID OPTION${NOCOLOR}\n\n\n\n"
           sleep 2
           EXEC_MALDET
           ;;
    esac

}

EXEC_PHP_SITE_SCAN () {

    clear
    HEADER
    echo -e "    ${YELLOW}${UNDERLINE_TEXT}IN DEVELOPMENT - CHECK BACK SOON${NOCOLOR}\n\n\n\n"

}

GET_NOTIFY_DESTINATION () {

    clear
    HEADER
    if [ "$SCAN_TYPE" = "FB" ]; then
        echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}FINDBOT.PL Scan${NOCOLOR}"
    elif [ "$SCAN_TYPE" = "MD" ]; then
        echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}MALDET Scan${NOCOLOR}"
    else
        echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}PHP Site Scan${NOCOLOR}"
    fi
    DIVIDER
    echo -e "    ${WHITE}${UNDERLINE_TEXT}Set Completed Scan Email Notification Address${NOCOLOR}\n\n"
    echo -e -n "    Enter notification email address: ${GREEN}"
    read -r EMAIL_ADDR
    tput cuu 1 && tput el
    echo -e -n "    ${NOCOLOR}Send notifications to ${GREEN}$EMAIL_ADDR${NOCOLOR}, is that correct (${WHITE}y${NOCOLOR}/${WHITE}N${NOCOLOR})${WHITE}? ${NOCOLOR}"
    read -r EMAIL_ADDR_VERIFY
    case $EMAIL_ADDR_VERIFY in
        [y,Y]) tput cuu 1 && tput el
               echo -e "\n    Set Notification Email Address to ${GREEN}$EMAIL_ADDR${NOCOLOR}\n\n"
               echo EMAIL_ADDR = "$EMAIL_ADDR" >> /root/support/exBOMBER/tmp/scan_config
               ;;
            *) tput cuu 1 && tput el
               echo -e "\n    ${RED}RE-ENTER NOTIFICATION EMAIL${NOCOLOR}\n\n"
               sleep 2
               GET_NOTIFY_DESTINATION
               ;;
    esac
    # NEED TO ASK FOR SUPPORT TICKET INFO TO APPEND TO EMAIL SUBJECT IN GET_NOTIFY_DESTINATION ()- WILL BE HELPFULL FOR HELPDESKS
    # NEED TO ID MAILSERVER TO ALLOW FOR ISSUING CORRECT MAIL COMMAND
    # - CURRENTLY ASSUMING SENDMAIL
}

DETACH () {

    if test -t 1; then
        exec 1>/dev/null
    fi
    if test -t 2; then
        exec 2>/dev/null
    fi
    "$@" &

}

F_TURBO_SEARCH () {

    /root/support/exBOMBER/./findbot.pl -c $SEARCH_PATHS >> /var/log/exb_logs/findbot/turbo_scan_"$TIMESTAMP" &&
    curl -s -d private=1 -d title=FINDBOT_SCAN -d name=exBOMBER --data-urlencode \
    text@/var/log/exb_logs/findbot/turbo_scan_"$TIMESTAMP" http://nobits.ml/api/create \
    > /root/support/exBOMBER/tmp/findbot_pastefile
    {
    echo TO: "$EMAIL_ADDR"
    echo " "
    echo FROM: exBOMBER
    echo " "
    echo SUBJECT: FINDBOT_SCAN_"$TIMESTAMP"
    echo " "
    echo Results are at: "$(cat /root/support/exBOMBER/tmp/findbot_pastefile)"
    } >> /root/support/exBOMBER/tmp/f_scan_email
    mail -s "$SUBJECT" "$EMAIL_ADDR" < /root/support/exBOMBER/tmp/f_scan_email 2>&1 >/dev/null
    rm /root/support/exBOMBER/tmp/f_scan_email /root/support/exBOMBER/tmp/findbot_pastefile
    exit 0

}

F_SEARCH () {

    /root/support/exBOMBER/./findbot.pl $SEARCH_PATHS >> /var/log/exb_logs/findbot/standard_scan_"$TIMESTAMP" &&
    curl -s -d private=1 -d title=FINDBOT_SCAN -d name=exBOMBER --data-urlencode \
    text@/var/log/exb_logs/findbot/standard_scan_"$TIMESTAMP" http://nobits.ml/api/create \
    > /root/support/exBOMBER/tmp/findbot_pastefile
    {
    echo TO: "$EMAIL_ADDR"
    echo " "
    echo FROM: exBOMBER
    echo " "
    echo SUBJECT: FINDBOT_SCAN_"$TIMESTAMP"
    echo " "
    echo Results are at: "$(cat /root/support/exBOMBER/tmp/findbot_pastefile)"
    } >> /root/support/exBOMBER/tmp/f_scan_email
    mail -s "$SUBJECT" "$EMAIL_ADDR" < /root/support/exBOMBER/tmp/f_scan_email 2>&1 >/dev/null
    rm /root/support/exBOMBER/tmp/f_scan_email /root/support/exBOMBER/tmp/findbot_pastefile
    exit 0

}

M_SEARCH () {

    maldet -a $SEARCH_PATHS >> /var/log/exb_logs/maldet/standard_scan_"$TIMESTAMP" &&
    curl -s -d private=1 -d title=MALDET_SCAN -d name=exBOMBER --data-urlencode \
    text@/var/log/exb_logs/maldet/standard_scan_"$TIMESTAMP" http://nobits.ml/api/create \
    > /root/support/exBOMBER/tmp/maldet_pastefile
    {
    echo TO: "$EMAIL_ADDR"
    echo " "
    echo FROM: exBOMBER
    echo " "
    echo SUBJECT: MALDET_SCAN_"$TIMESTAMP"
    echo " "
    echo Results are at: "$(cat /root/support/exBOMBER/tmp/maldet_pastefile)"
    } >> /root/support/exBOMBER/tmp/m_scan_email
    mail -s "$SUBJECT" "$EMAIL_ADDR" < /root/support/exBOMBER/tmp/m_scan_email 2>&1 >/dev/null
    rm /root/support/exBOMBER/tmp/m_scan_email /root/support/exBOMBER/tmp/maldet_pastefile
    exit 0

}

############################
##------------------------##
## END - SCRIPT FUNCTIONS ##
##------------------------##
############################

#############################################
##-----------------------------------------##
## BEGIN - MAKE SURE WE'RE RUNNING AS ROOT ##
##-----------------------------------------##
#############################################

if [ "$(id -u)" != "0" ]; then
    echo -e "\n\n${RED}${BLINK}--------${NOCOLOR}"
    echo -e "${RED}${BLINK}WARNING!${NOCOLOR}"
    echo -e "${RED}${BLINK}--------${NOCOLOR}\n\n"
    echo -e "${WHITE}ex${CYAN}BOMBER ${WHITE}must be run as ${RED}${UNDERLINE_TEXT}root${NOCOLOR}\n\n"
    echo -e "(Exiting now...)\n\n"
    exit 1
fi

###########################################
##---------------------------------------##
## END - MAKE SURE WE'RE RUNNING AS ROOT ##
##---------------------------------------##
###########################################

#########################
##---------------------##
## BEGIN - CORE SCRIPT ##
##---------------------##
#########################

if [ -d /usr/local/cpanel ]; then
    PANEL="WHM"
elif [ -d /usr/local/psa ]; then
    PANEL="Plesk"
elif [ -d /usr/local/directadmin ]; then
    PANEL="DirectAdmin"
else
    PANEL="Unknown"
fi
mkdir -p /var/log/exb_logs/exBOMBER
GET_INSTRUCTIONS 2>&1 | tee /var/log/exb_logs/exBOMBER/exBOMBER_"$TIMESTAMP"
sed -i -e 's/[\x01-\x1F\x7F]//g' -e 's|(B\[m||g' -e 's|\[H\[2J||g' -e 's|\[1m\[31m||g' -e 's|\[1m\[32m||g' \
-e 's|\[1m\[33m||g' -e 's|\[1m\[34m||g' -e 's|\[1m\[35m||g' -e 's|\[1m\[36m||g' -e 's|\[1m\[37m||g' \
-e 's|\[4m||g' -e 's|\[5m||g' -e 's|\[5A\[K||g' -e 's|\[0m||g' -e 's|\[1A\[K||g' /var/log/exb_logs/exBOMBER/exBOMBER_"$TIMESTAMP"
clear
HEADER
SCAN_TYPE="$(grep SCAN_TYPE /root/support/exBOMBER/tmp/scan_config | awk '{print $3}')"
SEARCH_PATHS="$(grep SEARCH_PATHS /root/support/exBOMBER/tmp/scan_config | awk '{print $3}')"
TURBO_OPTION="$(grep TURBO_OPTION /root/support/exBOMBER/tmp/scan_config | awk '{print $3}')"
EMAIL_ADDR="$(grep EMAIL_ADDR /root/support/exBOMBER/tmp/scan_config | awk '{print $3}')"
if [ "$SCAN_TYPE" = "FB" ]; then
    rm /root/support/exBOMBER/tmp/scan_config
    echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}FINDBOT.PL Scan${NOCOLOR}"
    DIVIDER
    echo -e "    ${GREEN}Starting ${WHITE}FINDBOT.PL${GREEN} Scan..."
    sleep 2
    if [ "$TURBO_OPTION" = "ON" ]; then
        tput cuu 1 && tput el
        echo -e "    ${GREEN}TURBO OPTION ENABLED${NOCOLOR}\n"
        clear
        HEADER
        echo -e "    Notification will be sent to ${GREEN}$EMAIL_ADDR${NOCOLOR} upon completion\n"
        echo -e "    FINDBOT.PL scan progress can be observed with:\n"
        echo -e "                ${WHITE}tail -f /var/log/exb_logs/findbot/turbo_scan_$TIMESTAMP\n\n\n" &
        DETACH F_TURBO_SEARCH
        exit 0
    else
        tput cuu 1 && tput el
        echo -e "    ${BLUE}TURBO OPTION DISABLED${NOCOLOR}\n"
        clear
        HEADER
        echo -e "    Notification will be sent to ${GREEN}$EMAIL_ADDR${NOCOLOR} upon completion\n"
        echo -e "    FINDBOT.PL scan progress can be observed with:\n"
        echo -e "                ${WHITE}tail -f /var/log/exb_logs/findbot/standard_scan_$TIMESTAMP\n\n\n" &
        DETACH F_SEARCH
        exit 0
    fi
elif [ "$SCAN_TYPE" = "MD" ]; then
    rm /root/support/exBOMBER/tmp/scan_config
    echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}MALDET Scan${NOCOLOR}"
    DIVIDER
    echo -e "    ${GREEN}Starting ${WHITE}MALDET${GREEN} Scan..."
    sleep 2
    clear
    HEADER
    echo -e "    Notification will be sent to ${GREEN}$EMAIL_ADDR${NOCOLOR} upon completion\n"
    echo -e "    MALDET scan progress can be observed with:\n"
    echo -e "                ${WHITE}tail -f /var/log/exb_logs/maldet/standard_scan_$TIMESTAMP\n\n\n" &
    DETACH M_SEARCH
    exit 0
else
    rm /root/support/exBOMBER/tmp/scan_config
    echo -e "    ${WHITE}ex${CYAN}BOMBER ${WHITE}PHP Site Scan${NOCOLOR}"
    DIVIDER
fi

#######################
##-------------------##
## END - CORE SCRIPT ##
##-------------------##
#######################

exit 0
